import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const config = {
  id: 24,
  chainId: "0x18",
  chainName: "KardiaChain Mainnet",
  nativeCurrency: {
    name: "KardiaChain",
    symbol: "KAI",
    decimals: 18
  },
  rpcUrls: ["https://rpc.kardiachain.io"],
  blockExplorerUrls: ["https://explorer.kardiachain.io"],
  multicallAddress: "0x1234567890abcdef1234567890abcdef12345678",
  // Additional helpful properties
  isTestnet: false,
  icon: "https://kardiachain.io/favicon.ico",
  networkType: "mainnet"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      </Providers>
    </html>
  );
}
